# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1350, 800)
        self.action_1 = QAction(MainWindow)
        self.action_1.setObjectName(u"action_1")
        font = QFont()
        font.setFamily(u"Times New Roman")
        font.setPointSize(16)
        self.action_1.setFont(font)
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.action_2.setFont(font)
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        self.action_exit.setFont(font)
        self.en_lang = QAction(MainWindow)
        self.en_lang.setObjectName(u"en_lang")
        self.en_lang.setFont(font)
        self.uk_lang = QAction(MainWindow)
        self.uk_lang.setObjectName(u"uk_lang")
        self.uk_lang.setFont(font)
        self.ru_lang = QAction(MainWindow)
        self.ru_lang.setObjectName(u"ru_lang")
        self.ru_lang.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 160, 691, 80))
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        self.horizontalLayoutWidget.setFont(font1)
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.all_time = QPushButton(self.horizontalLayoutWidget)
        self.all_time.setObjectName(u"all_time")
        self.all_time.setFont(font)

        self.horizontalLayout.addWidget(self.all_time)

        self.last_year = QPushButton(self.horizontalLayoutWidget)
        self.last_year.setObjectName(u"last_year")
        self.last_year.setFont(font)

        self.horizontalLayout.addWidget(self.last_year)

        self.horizontalLayoutWidget_2 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(20, 80, 691, 80))
        self.horizontalLayoutWidget_2.setFont(font1)
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.label = QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.horizontalLayout_2.addWidget(self.label)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.horizontalLayoutWidget_3 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(20, 0, 691, 80))
        self.horizontalLayoutWidget_3.setFont(font1)
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.label_5 = QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName(u"label_5")
        font2 = QFont()
        font2.setFamily(u"Times New Roman")
        font2.setPointSize(16)
        font2.setBold(True)
        self.label_5.setFont(font2)

        self.horizontalLayout_4.addWidget(self.label_5)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_4)

        self.horizontalLayoutWidget_4 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(20, 320, 782, 80))
        self.horizontalLayoutWidget_4.setFont(font1)
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font)

        self.horizontalLayout_5.addWidget(self.label_2)

        self.date_start = QDateEdit(self.horizontalLayoutWidget_4)
        self.date_start.setObjectName(u"date_start")
        self.date_start.setFont(font)

        self.horizontalLayout_5.addWidget(self.date_start)

        self.label_3 = QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font)

        self.horizontalLayout_5.addWidget(self.label_3)

        self.date_end = QDateEdit(self.horizontalLayoutWidget_4)
        self.date_end.setObjectName(u"date_end")
        self.date_end.setFont(font)

        self.horizontalLayout_5.addWidget(self.date_end)

        self.horizontalSpacer_5 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_5)

        self.horizontalLayoutWidget_5 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(20, 400, 691, 80))
        self.horizontalLayoutWidget_5.setFont(font1)
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_6)

        self.analyze = QPushButton(self.horizontalLayoutWidget_5)
        self.analyze.setObjectName(u"analyze")
        self.analyze.setFont(font)

        self.horizontalLayout_6.addWidget(self.analyze)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_7)

        self.horizontalLayoutWidget_7 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setObjectName(u"horizontalLayoutWidget_7")
        self.horizontalLayoutWidget_7.setGeometry(QRect(10, 240, 719, 80))
        self.horizontalLayoutWidget_7.setFont(font1)
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.last_6_month = QPushButton(self.horizontalLayoutWidget_7)
        self.last_6_month.setObjectName(u"last_6_month")
        self.last_6_month.setFont(font)

        self.horizontalLayout_3.addWidget(self.last_6_month)

        self.last_3_month = QPushButton(self.horizontalLayoutWidget_7)
        self.last_3_month.setObjectName(u"last_3_month")
        self.last_3_month.setFont(font)

        self.horizontalLayout_3.addWidget(self.last_3_month)

        self.last_month = QPushButton(self.horizontalLayoutWidget_7)
        self.last_month.setObjectName(u"last_month")
        self.last_month.setFont(font)

        self.horizontalLayout_3.addWidget(self.last_month)

        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(740, 10, 590, 670))
        self.tabWidget_2.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget = QTabWidget(self.tab)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-10, 0, 595, 640))
        self.tabWidget.setFont(font)
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.predict_table_1 = QTableWidget(self.tab_3)
        if (self.predict_table_1.columnCount() < 5):
            self.predict_table_1.setColumnCount(5)
        if (self.predict_table_1.rowCount() < 10):
            self.predict_table_1.setRowCount(10)
        self.predict_table_1.setObjectName(u"predict_table_1")
        self.predict_table_1.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_1.setFont(font)
        self.predict_table_1.setRowCount(10)
        self.predict_table_1.setColumnCount(5)
        self.predict_table_1.horizontalHeader().setVisible(False)
        self.predict_table_1.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_1.verticalHeader().setVisible(False)
        self.predict_table_1.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_1.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.predict_table_2 = QTableWidget(self.tab_4)
        if (self.predict_table_2.columnCount() < 5):
            self.predict_table_2.setColumnCount(5)
        if (self.predict_table_2.rowCount() < 10):
            self.predict_table_2.setRowCount(10)
        self.predict_table_2.setObjectName(u"predict_table_2")
        self.predict_table_2.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_2.setFont(font)
        self.predict_table_2.setRowCount(10)
        self.predict_table_2.setColumnCount(5)
        self.predict_table_2.horizontalHeader().setVisible(False)
        self.predict_table_2.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_2.verticalHeader().setVisible(False)
        self.predict_table_2.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_2.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.predict_table_3 = QTableWidget(self.tab_5)
        if (self.predict_table_3.columnCount() < 5):
            self.predict_table_3.setColumnCount(5)
        if (self.predict_table_3.rowCount() < 10):
            self.predict_table_3.setRowCount(10)
        self.predict_table_3.setObjectName(u"predict_table_3")
        self.predict_table_3.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_3.setFont(font)
        self.predict_table_3.setRowCount(10)
        self.predict_table_3.setColumnCount(5)
        self.predict_table_3.horizontalHeader().setVisible(False)
        self.predict_table_3.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_3.verticalHeader().setVisible(False)
        self.predict_table_3.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_3.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.predict_table_4 = QTableWidget(self.tab_6)
        if (self.predict_table_4.columnCount() < 5):
            self.predict_table_4.setColumnCount(5)
        if (self.predict_table_4.rowCount() < 10):
            self.predict_table_4.setRowCount(10)
        self.predict_table_4.setObjectName(u"predict_table_4")
        self.predict_table_4.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_4.setFont(font)
        self.predict_table_4.setRowCount(10)
        self.predict_table_4.setColumnCount(5)
        self.predict_table_4.horizontalHeader().setVisible(False)
        self.predict_table_4.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_4.verticalHeader().setVisible(False)
        self.predict_table_4.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_4.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.predict_table_5 = QTableWidget(self.tab_7)
        if (self.predict_table_5.columnCount() < 5):
            self.predict_table_5.setColumnCount(5)
        if (self.predict_table_5.rowCount() < 10):
            self.predict_table_5.setRowCount(10)
        self.predict_table_5.setObjectName(u"predict_table_5")
        self.predict_table_5.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_5.setFont(font)
        self.predict_table_5.setRowCount(10)
        self.predict_table_5.setColumnCount(5)
        self.predict_table_5.horizontalHeader().setVisible(False)
        self.predict_table_5.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_5.verticalHeader().setVisible(False)
        self.predict_table_5.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_5.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.predict_table_6 = QTableWidget(self.tab_8)
        if (self.predict_table_6.columnCount() < 5):
            self.predict_table_6.setColumnCount(5)
        if (self.predict_table_6.rowCount() < 10):
            self.predict_table_6.setRowCount(10)
        self.predict_table_6.setObjectName(u"predict_table_6")
        self.predict_table_6.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_6.setFont(font)
        self.predict_table_6.setRowCount(10)
        self.predict_table_6.setColumnCount(5)
        self.predict_table_6.horizontalHeader().setVisible(False)
        self.predict_table_6.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_6.verticalHeader().setVisible(False)
        self.predict_table_6.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_6.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.predict_table_7 = QTableWidget(self.tab_9)
        if (self.predict_table_7.columnCount() < 5):
            self.predict_table_7.setColumnCount(5)
        if (self.predict_table_7.rowCount() < 10):
            self.predict_table_7.setRowCount(10)
        self.predict_table_7.setObjectName(u"predict_table_7")
        self.predict_table_7.setGeometry(QRect(0, 0, 600, 610))
        self.predict_table_7.setFont(font)
        self.predict_table_7.setRowCount(10)
        self.predict_table_7.setColumnCount(5)
        self.predict_table_7.horizontalHeader().setVisible(False)
        self.predict_table_7.horizontalHeader().setDefaultSectionSize(125)
        self.predict_table_7.verticalHeader().setVisible(False)
        self.predict_table_7.verticalHeader().setCascadingSectionResizes(True)
        self.predict_table_7.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget.addTab(self.tab_9, "")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_3 = QTabWidget(self.tab_2)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(-10, 0, 595, 640))
        self.tabWidget_3.setFont(font)
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.cost_table_1 = QTableWidget(self.tab_10)
        if (self.cost_table_1.columnCount() < 5):
            self.cost_table_1.setColumnCount(5)
        if (self.cost_table_1.rowCount() < 10):
            self.cost_table_1.setRowCount(10)
        self.cost_table_1.setObjectName(u"cost_table_1")
        self.cost_table_1.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_1.setFont(font)
        self.cost_table_1.setRowCount(10)
        self.cost_table_1.setColumnCount(5)
        self.cost_table_1.horizontalHeader().setVisible(False)
        self.cost_table_1.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_1.verticalHeader().setVisible(False)
        self.cost_table_1.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_1.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.cost_table_2 = QTableWidget(self.tab_11)
        if (self.cost_table_2.columnCount() < 5):
            self.cost_table_2.setColumnCount(5)
        if (self.cost_table_2.rowCount() < 10):
            self.cost_table_2.setRowCount(10)
        self.cost_table_2.setObjectName(u"cost_table_2")
        self.cost_table_2.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_2.setFont(font)
        self.cost_table_2.setRowCount(10)
        self.cost_table_2.setColumnCount(5)
        self.cost_table_2.horizontalHeader().setVisible(False)
        self.cost_table_2.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_2.verticalHeader().setVisible(False)
        self.cost_table_2.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_2.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.cost_table_3 = QTableWidget(self.tab_12)
        if (self.cost_table_3.columnCount() < 5):
            self.cost_table_3.setColumnCount(5)
        if (self.cost_table_3.rowCount() < 10):
            self.cost_table_3.setRowCount(10)
        self.cost_table_3.setObjectName(u"cost_table_3")
        self.cost_table_3.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_3.setFont(font)
        self.cost_table_3.setRowCount(10)
        self.cost_table_3.setColumnCount(5)
        self.cost_table_3.horizontalHeader().setVisible(False)
        self.cost_table_3.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_3.verticalHeader().setVisible(False)
        self.cost_table_3.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_3.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.cost_table_4 = QTableWidget(self.tab_13)
        if (self.cost_table_4.columnCount() < 5):
            self.cost_table_4.setColumnCount(5)
        if (self.cost_table_4.rowCount() < 10):
            self.cost_table_4.setRowCount(10)
        self.cost_table_4.setObjectName(u"cost_table_4")
        self.cost_table_4.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_4.setFont(font)
        self.cost_table_4.setRowCount(10)
        self.cost_table_4.setColumnCount(5)
        self.cost_table_4.horizontalHeader().setVisible(False)
        self.cost_table_4.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_4.verticalHeader().setVisible(False)
        self.cost_table_4.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_4.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.cost_table_5 = QTableWidget(self.tab_14)
        if (self.cost_table_5.columnCount() < 5):
            self.cost_table_5.setColumnCount(5)
        if (self.cost_table_5.rowCount() < 10):
            self.cost_table_5.setRowCount(10)
        self.cost_table_5.setObjectName(u"cost_table_5")
        self.cost_table_5.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_5.setFont(font)
        self.cost_table_5.setRowCount(10)
        self.cost_table_5.setColumnCount(5)
        self.cost_table_5.horizontalHeader().setVisible(False)
        self.cost_table_5.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_5.verticalHeader().setVisible(False)
        self.cost_table_5.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_5.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tab_15 = QWidget()
        self.tab_15.setObjectName(u"tab_15")
        self.cost_table_6 = QTableWidget(self.tab_15)
        if (self.cost_table_6.columnCount() < 5):
            self.cost_table_6.setColumnCount(5)
        if (self.cost_table_6.rowCount() < 10):
            self.cost_table_6.setRowCount(10)
        self.cost_table_6.setObjectName(u"cost_table_6")
        self.cost_table_6.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_6.setFont(font)
        self.cost_table_6.setRowCount(10)
        self.cost_table_6.setColumnCount(5)
        self.cost_table_6.horizontalHeader().setVisible(False)
        self.cost_table_6.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_6.verticalHeader().setVisible(False)
        self.cost_table_6.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_6.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_15, "")
        self.tab_16 = QWidget()
        self.tab_16.setObjectName(u"tab_16")
        self.cost_table_7 = QTableWidget(self.tab_16)
        if (self.cost_table_7.columnCount() < 5):
            self.cost_table_7.setColumnCount(5)
        if (self.cost_table_7.rowCount() < 10):
            self.cost_table_7.setRowCount(10)
        self.cost_table_7.setObjectName(u"cost_table_7")
        self.cost_table_7.setGeometry(QRect(0, 0, 600, 610))
        self.cost_table_7.setFont(font)
        self.cost_table_7.setRowCount(10)
        self.cost_table_7.setColumnCount(5)
        self.cost_table_7.horizontalHeader().setVisible(False)
        self.cost_table_7.horizontalHeader().setDefaultSectionSize(125)
        self.cost_table_7.verticalHeader().setVisible(False)
        self.cost_table_7.verticalHeader().setCascadingSectionResizes(True)
        self.cost_table_7.verticalHeader().setMinimumSectionSize(60)
        self.tabWidget_3.addTab(self.tab_16, "")
        self.tabWidget_2.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1350, 30))
        font3 = QFont()
        font3.setFamily(u"Fira Sans")
        font3.setPointSize(16)
        self.menubar.setFont(font3)
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu.setFont(font3)
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.action_1)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.en_lang)
        self.menu_2.addAction(self.uk_lang)
        self.menu_2.addAction(self.ru_lang)

        self.retranslateUi(MainWindow)

        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u0421\u041f\u041f\u0420", None))
        self.action_1.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0443\u0442\u044c \u043a \u0431\u0434", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0447\u0430\u0441\u0430 \u0440\u0430\u0431\u043e\u0442\u044b", None))
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u0432\u044b\u0445\u043e\u0434", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
        self.en_lang.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.uk_lang.setText(QCoreApplication.translate("MainWindow", u"\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430", None))
        self.ru_lang.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0443\u0441\u0441\u043a\u0438\u0439", None))
        self.all_time.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u0432\u0441\u0451 \u0432\u0440\u0435\u043c\u044f", None))
        self.last_year.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439 \u0433\u043e\u0434", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u043a \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u0434\u043b\u044f \u0430\u043d\u0430\u043b\u0438\u0437\u0430", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0421\u041f\u041f\u0420", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0418\u043b\u0438 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0438\u0442\u0435 \u0441\u0432\u043e\u0439 \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u043a:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u2014", None))
        self.analyze.setText(QCoreApplication.translate("MainWindow", u"\u0410\u043d\u0430\u043b\u0438\u0437\u0438\u0440\u043e\u0432\u0430\u0442\u044c", None))
        self.last_6_month.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 6 \u043c\u0435\u0441\u044f\u0446\u0435\u0432", None))
        self.last_3_month.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 3 \u043c\u0435\u0441\u044f\u0446\u0430", None))
        self.last_month.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439 \u043c\u0435\u0441\u044f\u0446", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u041f\u043d", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u0412\u0442", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u0421\u0440", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"\u0427\u0442", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"\u041f\u0442", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"\u0421\u0431", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"\u0412\u0441", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0433\u043d\u043e\u0437\u044b", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"\u041f\u043d", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"\u0412\u0442", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"\u0421\u0440", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), QCoreApplication.translate("MainWindow", u"\u0427\u0442", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), QCoreApplication.translate("MainWindow", u"\u041f\u0442", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_15), QCoreApplication.translate("MainWindow", u"\u0421\u0431", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_16), QCoreApplication.translate("MainWindow", u"\u0412\u0441", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u041c\u0435\u043d\u044e", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u042f\u0437\u044b\u043a", None))
    # retranslateUi

